// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.GoogleDriveUpload.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.GoogleDriveUpload;
    using Lykke.Service.GoogleDriveUpload.Client;
    using Lykke.Service.GoogleDriveUpload.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FilePermission
    {
        /// <summary>
        /// Initializes a new instance of the FilePermission class.
        /// </summary>
        public FilePermission()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FilePermission class.
        /// </summary>
        /// <param name="role">Possible values include: 'Unknown', 'Organizer',
        /// 'Owner', 'Writer', 'Commenter', 'Reader'</param>
        public FilePermission(string googleId = default(string), string domain = default(string), string emailAddress = default(string), System.DateTime? expirationTime = default(System.DateTime?), Role? role = default(Role?))
        {
            GoogleId = googleId;
            Domain = domain;
            EmailAddress = emailAddress;
            ExpirationTime = expirationTime;
            Role = role;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GoogleId")]
        public string GoogleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Domain")]
        public string Domain { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmailAddress")]
        public string EmailAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpirationTime")]
        public System.DateTime? ExpirationTime { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Unknown', 'Organizer',
        /// 'Owner', 'Writer', 'Commenter', 'Reader'
        /// </summary>
        [JsonProperty(PropertyName = "Role")]
        public Role? Role { get; set; }

    }
}
