// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.GoogleDriveUpload.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.GoogleDriveUpload;
    using Lykke.Service.GoogleDriveUpload.Client;
    using Lykke.Service.GoogleDriveUpload.Client.AutorestClient;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetAllFolderPathsResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetAllFolderPathsResponse class.
        /// </summary>
        public GetAllFolderPathsResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetAllFolderPathsResponse class.
        /// </summary>
        public GetAllFolderPathsResponse(IList<FolderPath> paths = default(IList<FolderPath>))
        {
            Paths = paths;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Paths")]
        public IList<FolderPath> Paths { get; set; }

    }
}
