// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Service.GoogleDriveUpload.Client.AutorestClient.Models
{
    using Lykke.Service;
    using Lykke.Service.GoogleDriveUpload;
    using Lykke.Service.GoogleDriveUpload.Client;
    using Lykke.Service.GoogleDriveUpload.Client.AutorestClient;
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class UploadFileModel
    {
        /// <summary>
        /// Initializes a new instance of the UploadFileModel class.
        /// </summary>
        public UploadFileModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UploadFileModel class.
        /// </summary>
        public UploadFileModel(string fileData, string fileName, string parentFolderGoogleId)
        {
            FileData = fileData;
            FileName = fileName;
            ParentFolderGoogleId = parentFolderGoogleId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileData")]
        public string FileData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ParentFolderGoogleId")]
        public string ParentFolderGoogleId { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (FileData == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FileData");
            }
            if (FileName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FileName");
            }
            if (ParentFolderGoogleId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ParentFolderGoogleId");
            }
        }
    }
}
